### ISSUE TITLE
POST ile parse işlemi gerçekleşmiyor.

### ISSUE THREAD

**Issue by emresekeroglu** [abugraokkali/Rest-API#1]
Merhaba windows üzerinde uygulamanızı eğitim amaçlı test etmek istedim fakat post metodu ile kullanıcı bilgilerini parse edemiyorum.

**Comment by abugraokkali** [comment]
https://github.com/abugraokkali/Rest-API/commit/9dc3fcefb687eaeb786378e35a3c3e9accebba11 ile çözüldü
